# see https://www.tomasvotruba.com/blog/2020/02/24/how-many-days-of-technical-debt-has-your-php-project
# .github/workflows/sonarcube.yaml
name: Sonar

on: push

jobs:
    sonar_cloud:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@master
                with:
                    # sonar needs non-shallow clone
                    fetch-depth: 10000

            -   uses: sonarsource/sonarcloud-github-action@master
                env:
                    GITHUB_TOKEN: ${{ secrets.SONAR_TOKEN }}
                    ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}