name: Split Tests

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    after_split_testing:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                package_name:
                    - class-presence
                    - config-transformer
                    - latte-to-twig
                    - template-checker
                    - vendor-patches
                    # Github Actions buggy now
                    # - easy-ci
                    # - fatal-error-scanner
                    # - neon-to-yaml
                    # - psr4-switcher
                    # - symfony-route-usage

        name: Split Tests of ${{ matrix.package_name }}

        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            # only install monorepo-builder
            -   run: |
                    composer update --ansi
                    vendor/bin/monorepo-builder localize-composer-paths --ansi

            -   run: |
                    cd packages/${{ matrix.package_name }}
                    composer update --no-progress --ansi

            -   run: |
                    cd packages/${{ matrix.package_name }}
                    vendor/bin/phpunit
